Repository Metatavu/metaform-management-portal, pull requests merged in 2022-10, with the labels that each got.

#176 Feature 175 localization fix
  src/components/editor/editor-screen-table.tsx
  src/components/generic/form-autocomplete.tsx
  src/components/layouts/breadcrumbs/breadcrumbs.tsx
  src/components/layouts/breadcrumbs/routes.ts
  src/components/screens/forms/form-history-screen.tsx
  src/components/screens/forms/form-replies-screen.tsx
  src/components/screens/forms/forms-data-screen.tsx
  src/components/screens/forms/forms-screen.tsx
  src/components/users/users-table.tsx
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
Labels: bug

#187 Feature 177 visibility refining
  src/components/editor/metaform-editor-left-drawer.tsx
  src/components/editor/metaform-editor-right-drawer-feature.tsx
  src/components/editor/metaform-editor-right-drawer-visibility.tsx
  src/components/editor/metaform-editor-right-drawer.tsx
  src/components/editor/metaform-editor.tsx
  src/components/generic/tab-panel.tsx
  src/components/preview/draft-preview.tsx
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
  src/styled/editor/metaform-editor.tsx
  src/types/index.ts
  src/utils/localization-utils.ts
  src/utils/metaform-utils.ts
  src/utils/sosmeta-utils.ts
Labels: enhancement

#192 Fixed new versions creation bug
  src/components/screens/editor/editor-screen.tsx
Labels: bug

#196 fixed loss focus
  src/components/editor/metaform-editor-left-drawer.tsx
  src/components/editor/metaform-editor-right-drawer-feature.tsx
Labels: bug

#189 Status field created on new forms
  src/components/screens/editor/draft-editor-screen.tsx
  src/utils/metaform-utils.ts
Labels: enhancement

#198 html editor
  package-lock.json
  package.json
  src/components/editor/field-renderer/addable-field-renderer.tsx
  src/components/editor/metaform-editor-right-drawer-feature.tsx
  src/components/editor/metaform-editor.tsx
  src/components/screens/editor/editor-screen.tsx
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
  src/metaform-react/MetaformEditableHtmlComponent.tsx
  src/metaform-react/MetaformHtmlComponent.tsx
  src/utils/metaform-utils.ts
Labels: enhancement

#222 fixed permission group selection and code refining
  src/components/editor/metaform-editor-right-drawer-feature.tsx
  src/types/index.ts
  src/utils/metaform-utils.ts
Labels: bug

#218 Last modifiers email is now correctly retrieved and displayed.
  src/api/index.ts
  src/components/editor/editor-screen-table.tsx
  src/components/screens/editor/editor-screen.tsx
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
  tsconfig.json
Labels: enhancement

#227 changed interval
  src/components/containers/authentication-provider.tsx
Labels: bug

#231 Renamed metaform-admin to system-admin as SYSTEM_ADMIN_ROLE
  src/types/index.ts
Labels: bug

#238 fixed
  src/components/editor/metaform-editor-right-drawer-feature.tsx
  src/components/screens/editor/draft-editor-screen.tsx
Labels: bug

#246 UI improvements
  src/app/store.ts
  src/components/contexts/error-handler.tsx
  src/components/editor/editor-screen-drawer.tsx
  src/components/editor/editor-screen-table.tsx
  src/components/layouts/admin-layout.tsx
  src/components/screens/editor/draft-editor-screen.tsx
  src/components/screens/editor/editor-screen.tsx
  src/components/screens/forms/form-history-screen.tsx
  src/components/screens/forms/form-replies-screen.tsx
  src/components/screens/forms/form-reply-screen.tsx
  src/components/screens/forms/forms-data-screen.tsx
  src/components/screens/forms/forms-screen.tsx
  src/components/screens/users/users-screen.tsx
  src/components/users/users-table.tsx
  src/features/snackbar-slice.ts
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
Labels: enhancement

#249 Feature 248 check metaform manager role
  src/app/hooks.ts
  src/components/containers/authentication-provider.tsx
  src/components/screens/editor/editor-screen.tsx
  src/components/screens/forms/form-replies-screen.tsx
  src/consts/index.ts
  src/features/auth-slice.ts
  src/utils/auth-utils.ts
Labels: bug, enhancement
